import { AnimalTemplate } from '@/types';

export const ANIMAL_TEMPLATES: AnimalTemplate[] = [
  {
    animalName: 'Red Fox',
    scientificName: 'Vulpes vulpes',
    description:
      'A highly adaptable omnivore renowned for its cunning intelligence and striking auburn coat. Capable of thriving across diverse ecosystems from arctic tundra to urban centres.',
    habitat: 'Woodland edges, farmland, and increasingly urban environments',
    diet: 'Omnivorous — small mammals, birds, fruits, earthworms, and scavenged refuse',
    behavior: 'Largely crepuscular; solitary hunter with complex vocal communication including 40 distinct calls',
    rarity: 'Uncommon',
    biome: 'Forest',
    baseStats: { power: 55, agility: 78, intelligence: 82, camouflage: 60, friendliness: 35, rarityScore: 42 },
  },
  {
    animalName: 'White-tailed Deer',
    scientificName: 'Odocoileus virginianus',
    description:
      'North America\'s most widespread large ungulate, identifiable by the distinctive white underside of its tail raised as a warning signal. Bucks grow elaborate antlers shed annually.',
    habitat: 'Mixed forests, meadows, and forest edge habitats',
    diet: 'Herbivorous — grasses, legumes, leaves, fungi, acorns, and agricultural crops',
    behavior: 'Crepuscular and generally timid; communicates via scent glands, vocalizations, and visual posturing',
    rarity: 'Common',
    biome: 'Forest',
    baseStats: { power: 62, agility: 85, intelligence: 45, camouflage: 55, friendliness: 40, rarityScore: 20 },
  },
  {
    animalName: 'Rock Pigeon',
    scientificName: 'Columba livia',
    description:
      'Originally a cliff-dwelling bird domesticated over 5,000 years ago, the rock pigeon is now one of the world\'s most successful urban colonisers. Remarkable magnetoreception enables long-distance navigation.',
    habitat: 'Urban centres, bridges, cliff faces, and agricultural grain stores',
    diet: 'Granivorous — seeds, grains, discarded human food, and occasional invertebrates',
    behavior: 'Gregarious; forms flocks with complex flock dynamics; monogamous with long-term pair bonds',
    rarity: 'Common',
    biome: 'Urban',
    baseStats: { power: 22, agility: 70, intelligence: 55, camouflage: 30, friendliness: 65, rarityScore: 10 },
  },
  {
    animalName: 'Eastern Grey Squirrel',
    scientificName: 'Sciurus carolinensis',
    description:
      'A highly successful arboreal rodent with exceptional spatial memory allowing it to relocate thousands of cached food items. Its scatter-hoarding behaviour makes it a key forest regeneration agent.',
    habitat: 'Deciduous and mixed woodlands, parks, and tree-lined urban streets',
    diet: 'Primarily granivorous — acorns, nuts, seeds, fungi, bark, and occasional bird eggs',
    behavior: 'Diurnal; displays elaborate deceptive caching behaviour to mislead food thieves',
    rarity: 'Common',
    biome: 'Forest',
    baseStats: { power: 20, agility: 88, intelligence: 70, camouflage: 50, friendliness: 55, rarityScore: 15 },
  },
  {
    animalName: 'European Robin',
    scientificName: 'Erithacus rubecula',
    description:
      'A small insectivorous bird celebrated for its vivid orange-red breast and melodious year-round song. Robins are unusually territorial among songbirds, fiercely defending feeding areas.',
    habitat: 'Woodland understory, hedgerows, parks, and garden shrubbery',
    diet: 'Insectivorous — earthworms, beetles, ants, and small berries in winter',
    behavior: 'Solitary outside breeding season; highly bold and curious around human activity',
    rarity: 'Common',
    biome: 'Forest',
    baseStats: { power: 14, agility: 72, intelligence: 58, camouflage: 35, friendliness: 80, rarityScore: 18 },
  },
  {
    animalName: 'Mute Swan',
    scientificName: 'Cygnus olor',
    description:
      'One of the heaviest flying birds in the world, the mute swan is distinguished by its gracefully curved neck and orange-red beak with characteristic black knob. Despite its name it produces a range of hisses and snorts.',
    habitat: 'Lakes, slow-moving rivers, estuaries, and coastal lagoons',
    diet: 'Primarily herbivorous — submerged aquatic vegetation, algae, and occasional invertebrates',
    behavior: 'Territorial and aggressive when nesting; forms lifelong pair bonds with complex courtship rituals',
    rarity: 'Uncommon',
    biome: 'Wetland',
    baseStats: { power: 75, agility: 40, intelligence: 52, camouflage: 20, friendliness: 28, rarityScore: 38 },
  },
  {
    animalName: 'Mallard Duck',
    scientificName: 'Anas platyrhynchos',
    description:
      'The progenitor of most domestic duck breeds, the mallard is among the most widely distributed waterfowl globally. Males display striking iridescent green plumage during breeding season.',
    habitat: 'Ponds, rivers, wetlands, coastal areas, and urban parks with water bodies',
    diet: 'Omnivorous — aquatic plants, seeds, insects, worms, small fish, and scavenged food',
    behavior: 'Social and highly adaptable; migratory in northern populations; females give the iconic quacking call',
    rarity: 'Common',
    biome: 'Wetland',
    baseStats: { power: 30, agility: 65, intelligence: 48, camouflage: 55, friendliness: 72, rarityScore: 12 },
  },
  {
    animalName: 'Western European Hedgehog',
    scientificName: 'Erinaceus europaeus',
    description:
      'A nocturnal insectivore covered in approximately 5,000 to 7,000 keratin spines used for defence. Hibernates from November to March, building up critical fat reserves in autumn.',
    habitat: 'Hedgerows, woodland edges, suburban gardens, and farmland margins',
    diet: 'Insectivorous — beetles, earthworms, caterpillars, slugs, and occasional small vertebrates',
    behavior: 'Solitary and nocturnal; produces a distinctive snuffling locomotion; rolls into a protective ball when threatened',
    rarity: 'Rare',
    biome: 'Forest',
    baseStats: { power: 28, agility: 30, intelligence: 42, camouflage: 65, friendliness: 58, rarityScore: 62 },
  },
  {
    animalName: 'Domestic Horse',
    scientificName: 'Equus ferus caballus',
    description:
      'Domesticated approximately 6,000 years ago on the Eurasian steppes, the horse transformed human civilisation through transport, agriculture, and warfare. Possesses a wide-angle visual field of nearly 350 degrees.',
    habitat: 'Managed pastures, stables, and semi-wild grassland in feral populations',
    diet: 'Strictly herbivorous — grasses, hay, oats, and supplementary vegetation',
    behavior: 'Social herd animal with complex communication; capable of reading human emotional expression',
    rarity: 'Uncommon',
    biome: 'Grassland',
    baseStats: { power: 92, agility: 82, intelligence: 68, camouflage: 20, friendliness: 75, rarityScore: 35 },
  },
  {
    animalName: 'Domestic Cat',
    scientificName: 'Felis catus',
    description:
      'One of the world\'s most successful predators and most popular companion animals. Despite domestication, retains nearly all ancestral predatory instincts and hunting techniques.',
    habitat: 'Human dwellings, farmyards, feral colonies in urban and rural environments',
    diet: 'Obligate carnivore — small mammals, birds, reptiles, and commercial pet food',
    behavior: 'Crepuscular; semi-solitary; communicates with humans through unique meow vocalisations not used with other cats',
    rarity: 'Common',
    biome: 'Urban',
    baseStats: { power: 45, agility: 90, intelligence: 72, camouflage: 60, friendliness: 55, rarityScore: 10 },
  },
  {
    animalName: 'Domestic Dog',
    scientificName: 'Canis lupus familiaris',
    description:
      'The first domesticated animal, diverging from wolves over 15,000 years ago through a mutual relationship with humans. Possesses extraordinary social intelligence and ability to read human gestures.',
    habitat: 'Human settlements globally; feral populations in suburban and rural areas',
    diet: 'Omnivorous — commercial pet food, table scraps, small prey when feral',
    behavior: 'Highly social pack animal; forms strong interspecies bonds; communicates through over 100 facial expressions',
    rarity: 'Common',
    biome: 'Urban',
    baseStats: { power: 60, agility: 75, intelligence: 80, camouflage: 30, friendliness: 95, rarityScore: 8 },
  },
  {
    animalName: 'Highland Cattle',
    scientificName: 'Bos taurus',
    description:
      'Originating in the Scottish Highlands, this hardy breed is characterised by its long flowing coat and sweeping horns. The double-layered coat allows survival in extreme highland conditions.',
    habitat: 'Open pastures, upland moors, and hill farming landscapes',
    diet: 'Strictly herbivorous — grasses, heather, rushes, and coarse upland vegetation',
    behavior: 'Docile herd animal; highly cold-tolerant; uses horns to dig through snow to reach vegetation',
    rarity: 'Uncommon',
    biome: 'Grassland',
    baseStats: { power: 80, agility: 35, intelligence: 40, camouflage: 25, friendliness: 65, rarityScore: 40 },
  },
  {
    animalName: 'Common Brimstone Butterfly',
    scientificName: 'Gonepteryx rhamni',
    description:
      'One of Britain\'s longest-lived butterflies, surviving up to thirteen months. Its leaf-like wing shape provides exceptional camouflage at rest. Often the first butterfly seen after winter hibernation.',
    habitat: 'Woodland clearings, hedgerows, gardens, and scrubland with buckthorn',
    diet: 'Adult: nectar from flowers; larval: buckthorn and alder buckthorn leaves',
    behavior: 'Solitary; hibernates as adult in ivy or holly; male is brilliant yellow, female pale greenish-white',
    rarity: 'Uncommon',
    biome: 'Forest',
    baseStats: { power: 5, agility: 62, intelligence: 22, camouflage: 85, friendliness: 50, rarityScore: 45 },
  },
  {
    animalName: 'Carrion Crow',
    scientificName: 'Corvus corone',
    description:
      'Among the most cognitively advanced birds, capable of tool use, facial recognition of humans, and planning future events. Demonstrates complex social behaviour including funerals for deceased flock members.',
    habitat: 'Farmland, woodland, coastal cliffs, and urban environments',
    diet: 'Omnivorous scavenger — carrion, invertebrates, eggs, grains, and human waste',
    behavior: 'Intelligent and adaptable; uses cars to crack hard-shelled nuts on roads; highly suspicious of humans',
    rarity: 'Common',
    biome: 'Urban',
    baseStats: { power: 38, agility: 68, intelligence: 95, camouflage: 45, friendliness: 20, rarityScore: 22 },
  },
  {
    animalName: 'Tawny Owl',
    scientificName: 'Strix aluco',
    description:
      'Britain\'s most common owl and the source of the classic "twit-twoo" sound — actually a duet between male and female. Completely silent in flight due to comb-like serrations on primary feathers.',
    habitat: 'Deciduous woodland, parks, orchards, and areas with mature trees',
    diet: 'Carnivorous — small mammals (especially wood mice and voles), birds, earthworms, frogs',
    behavior: 'Strictly nocturnal; highly territorial; hunts by sound in complete darkness using asymmetric ears',
    rarity: 'Rare',
    biome: 'Forest',
    baseStats: { power: 55, agility: 70, intelligence: 80, camouflage: 90, friendliness: 15, rarityScore: 65 },
  },
  {
    animalName: 'European Rabbit',
    scientificName: 'Oryctolagus cuniculus',
    description:
      'Native to the Iberian Peninsula and now globally distributed, the European rabbit is the only species of rabbit to be domesticated. Creates complex underground burrow systems called warrens.',
    habitat: 'Grassland, heathland, woodland edges, coastal dunes, and farmland',
    diet: 'Herbivorous — grasses, clover, wildflowers, cereal crops, and bark in winter',
    behavior: 'Highly social; lives in hierarchical warren colonies; thumps hind feet to signal danger',
    rarity: 'Common',
    biome: 'Grassland',
    baseStats: { power: 18, agility: 82, intelligence: 45, camouflage: 60, friendliness: 62, rarityScore: 15 },
  },
  {
    animalName: 'Common Frog',
    scientificName: 'Rana temporaria',
    description:
      'The most common amphibian in northern Europe, capable of surviving partial freezing during hibernation. Males develop distinctive nuptial pads on thumbs to grip females during amplexus.',
    habitat: 'Ponds, ditches, marshes, damp grassland, and woodland during non-breeding season',
    diet: 'Insectivorous — flies, beetles, ants, worms, and slugs; tadpoles are herbivorous',
    behavior: 'Largely solitary; explosive breeding aggregations form in early spring; capable of limited thermoregulation',
    rarity: 'Uncommon',
    biome: 'Wetland',
    baseStats: { power: 12, agility: 70, intelligence: 30, camouflage: 80, friendliness: 42, rarityScore: 38 },
  },
  {
    animalName: 'Peregrine Falcon',
    scientificName: 'Falco peregrinus',
    description:
      'The fastest animal on Earth, reaching diving speeds exceeding 320 km/h during aerial hunts. Recovered from near-extinction caused by pesticide accumulation; now nesting on city skyscrapers globally.',
    habitat: 'Coastal cliffs, mountain crags, tall urban buildings, and open country',
    diet: 'Strictly carnivorous — medium-sized birds captured in high-speed aerial stoops',
    behavior: 'Solitary and highly territorial; pair bonds return to same nesting site annually; acute vision detects prey at 3 km',
    rarity: 'Epic',
    biome: 'Mountain',
    baseStats: { power: 85, agility: 99, intelligence: 75, camouflage: 50, friendliness: 10, rarityScore: 78 },
  },
  {
    animalName: 'European Otter',
    scientificName: 'Lutra lutra',
    description:
      'A semi-aquatic mustelid with dense waterproof fur and webbed feet, perfectly adapted for hunting in fast-flowing rivers. After near-extinction due to pollution and hunting, populations are recovering across Europe.',
    habitat: 'Clean unpolluted rivers, lakes, estuaries, and coastal marine habitats',
    diet: 'Piscivorous — primarily fish, supplemented by crustaceans, amphibians, and waterbirds',
    behavior: 'Largely solitary and crepuscular; maintains large riverine territories; playful behaviour often observed in juveniles',
    rarity: 'Epic',
    biome: 'Wetland',
    baseStats: { power: 60, agility: 88, intelligence: 78, camouflage: 55, friendliness: 40, rarityScore: 80 },
  },
  {
    animalName: 'Golden Eagle',
    scientificName: 'Aquila chrysaetos',
    description:
      'One of the most powerful raptors in the Northern Hemisphere, the golden eagle is revered across cultures as a symbol of strength and freedom. Wingspan reaching 2.3 metres allows effortless thermal soaring.',
    habitat: 'Remote mountain ranges, open moorland, and boreal forest wilderness',
    diet: 'Apex carnivore — hares, rabbits, grouse, and occasionally young deer or livestock',
    behavior: 'Territorial apex predator; performs dramatic sky-dancing courtship displays; same nest sites used for decades',
    rarity: 'Legendary',
    biome: 'Mountain',
    baseStats: { power: 95, agility: 90, intelligence: 82, camouflage: 45, friendliness: 5, rarityScore: 95 },
  },
];
